### ISSUE TITLE
Add reset commands to openhab-cli

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#104]
Two commands would be useful here:

One that resets the files in `userdata/etc` to the packaged versions. Possibly by deleting them then restoring them with conf-miss (and whatever the rpm equivalent is) 

One that resets ownership of everything to `openhab:openhab` @ThomDietrich, I understand that openhabian already does this. Would it make sense to reuse code here?

**Comment by ThomDietrich** [comment]
(1) sounds meaningful 👍 

(2) openHABian does a bit more than that because it also makes sure that the user has write access regardless how the last change happened. https://github.com/openhab/openhabian/blob/master/functions/system.sh#L159

**Comment by BClark09** [comment]
The need for (1) is not longer necessary as we have reduced the number of configuration files in `userdata/etc`.

(2) has been implements with `openhab-cli reset-ownership` which can be run by APT/YUM users and won't break anything offered by openHABian.
