### ISSUE TITLE
Unlinked Channels after restart ObenHab

### ISSUE THREAD

**Issue by DJDeepT** [openhab/openhab-linuxpkg#106]
Hello.
Since installing Openhabian 1.4 with Stable 2.2 i see, that some Linked Channels in PaperUI are unlinked after a Reboot or restart. Not always the same things/channels. Different Bindings.

What can i do here? Sometimes i have to restart my pi and then i can't always go through all Things (more than ~130) and check all Linked Items.

Do You Know the Problem?

Thanks

Tobi

**Comment by BClark09** [comment]
Hi Tobi,

You might get better results asking on the [community forums](https://community.openhab.org/). This github repo is for the Linux installation packages and I don't think it's related.

When you make a post, add the results of relevent information in the logs and the command `openhab-cli info`  as debugging information, perhaps someone experienced a similar issue. Remember to enclose copy-pasted information like the following:

````
```
< Insert Info Here >
```
````
