### ISSUE TITLE
"apt-get upgrade" reinstalls same version

### ISSUE THREAD

**Issue by NolanGarrett** [openhab/openhab-linuxpkg#11]
This may be by design, but on the cutting edge cloudbees apt configuration, each time you run `apt-get upgrade`, apt-get will reinstall OH2 regardless of whether the repo version is the same as the current version.

**Comment by theoweiss** [comment]
We plan to move the snapshot repo to bintray/jfrog. If this issue won't disappear as soon we've done the move please reopen this issue.

**Comment by BClark09** [comment]
The good news is that the initial tests understand versioning, so this is unlikely going to be the case during the move.
