### ISSUE TITLE
Upgrade of OH2 package resets startup configuration

### ISSUE THREAD

**Issue by NolanGarrett** [openhab/openhab-linuxpkg#13]
Perhaps this is by design, however, if you install openhab2-online via apt-get on Ubuntu, then disable on-boot startup of OH2 via systemctl disable openhab2, the next time you upgrade your package via apt-get openhab2 will again be set to start on boot (and will even be started at the end of the upgrade process). Tested on Ubuntu 16.04.1 LTS.

**Comment by BClark09** [comment]
Hi @NolanGarrett, apologies for the delay. The latest versions of the Linux Package won't restart if openHAB wasn't running to begin with. Since the feature is new, the first update won't restart regardless, but will prompt you in doing so manually.
