### ISSUE TITLE
Add openhab to the recommended permission groups

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#140]
Related to https://github.com/openhab/openhab-docs/pull/877. Lately, I have seen very little reason not to do this from within the package. 

@openhab/openhabian-maintainers, this is taken care of in openHABian, but I believe the basic set of permission groups should be set by the package here. WDYT?

`postinst` would need something like:

```sh
for pGroup in bluetooth tty dialout audio
do
  if [ $(getent group ${pGroup}) ]; then
    adduser openhab $pGroup
    ## or ##
    usermod -a -G $pGroup openhab
  fi
done
```

**Comment by EliasGabrielsson** [comment]
I am positive to this. 

I think it's time rethink what should be in `openhab/openhab-linuxpkg` vs `openhab/openhabian`.
I prefer to streamline openhabian's focus to more become of pre-packed, integrated and tested image supporting a specific set of hardware (currently Raspberry Pi and Pine64). In some sense should openhabian be "enduser" oriented, eg. it helps the non-linux experinced user to install and configure the openhab-linuxpkg. 

@ThomDietrich wdyt?

**Comment by BClark09** [comment]
It's come up before but I wasn't too sure how to define a line as such. To me, `openhab-linuxpkg` should do its best to get openHAB working out the box with any flavour of Linux regardless of the other tools or preferences installed on the system. openHABian is the tool used to easily integrate openHAB with other services and features, as well as making it easier for non-Linux users to get started.

**Comment by EliasGabrielsson** [comment]
Then we have the same opinion, that's a good start.
I did actually thought about the Java installation. Does the `openhab-linuxpkg` have a fallback dependency if Java aren't present on the system installing the package?
Eg. are there any dependencies to `openjdk` or similar?

Another aspect is the relationship between `openhab-cli` and `openhabian-config`. What should the longterm goal be for that?

**Comment by BClark09** [comment]
> Does the openhab-linuxpkg have a fallback dependency if Java aren't present on the system installing the package?

Unfortunately not, if there's no packaged version of Java installed, apt or yum will suggest it at the install stage, we can't install it automatically because there's too many varieties of Java (see https://github.com/openhab/openhab-linuxpkg/issues/123). The package will however show a warning at the end of the install if no valid Java install can be detected.

> Another aspect is the relationship between openhab-cli and openhabian-config. What should the longterm goal be for that?

This is where that line blurs I think, I only intended `openhab-cli` to be used as a set of shortcuts to the executables found in the `$OPENHAB_RUNTIME` folder. However, `showlogs`, `clean-cache` and `info` have proved to be very beneficial. I still believe that `openhab-cli` should only touch or show things controlled by the `openhab` package though. That way, I think openhabian-config should call openhab-cli for openHAB information, and have its own scripts for everything else.
