### ISSUE TITLE
Add zip and unzip packages to list of recommended software

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#141]
Prompted by https://community.openhab.org/t/raspberry-pi-3-b-and-debian-vm-setup-guides/65875

`zip` and `unzip` are not necessarily installed by default on Linux distributions. It should be installed by default with openHAB through the packaging system because `backup` and `restore` depend on them.

openHAB runs perfectly okay without them, and using `backup` and `restore` commands will prompt for an installation of `zip`/`unzip` if not found, so the packages should be recommended and not added as a strict dependency.

@openhab/openhabian-maintainers I believe openHABian installs `zip` and `unzip` packages through other recommendations and dependencies. So should not affect the install.

**Comment by BClark09** [comment]
Package built with changes:

```
 Package: openhab2
 Source: openhab2
 Version: 2.5.0~20190128205215-1
 Section: java
 Priority: optional
 Architecture: all
 Depends: adduser
 Recommends: zip, unzip
 Suggests: zulu-8 | zulu-embedded-8 | oracle-java8-installer |  openjdk-8-jdk-headless
 Conflicts: openhab2-online, openhab2-offline
 Installed-Size: 77907
 Maintainer: https://community.openhab.org
 Description: openhab2
  Linux installation package for openHAB 2.
 Homepage: www.openhab.org
```

**Comment by EliasGabrielsson** [comment]
Yes,`zip` is installed in openhabian.
