### ISSUE TITLE
Debian packages lack dependency on java

### ISSUE THREAD

**Issue by Ambytes** [openhab/openhab-linuxpkg#147]
Debian packages are missing a required dependency on java. Following installation steps on a blank debian works but the service is unable to start since java is missing.

Adding "Depends: openjdk-8-jre" should solve that issue.

**Comment by wborn** [comment]
See also https://github.com/openhab/openhab-linuxpkg/issues/123

**Comment by BClark09** [comment]
I'll close this issue based off of the comments in #123, but please let us know if have anything to add :)
