### ISSUE TITLE
Double startup ?

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-linuxpkg#164]
Hi @BClark09 ,

given the need to start OH *twice* after install/upgrade/cache clean as explained in #161 

**and** this

https://community.openhab.org/t/2-5-issues-after-upgrade/91287/7

I've come to think that it could be a good idea to build this double-start into the OH start script, 
Maybe something like "if cache dir is empty (=first start after install), issue restart after 5 mins".
Wdyt?

**Comment by BClark09** [comment]
Sorry for not getting back to you on this one.

This is an issue that effects everyone regardless of installation method right? I am not keen in adding workarounds that mask an issue for a specific set of people. The openHAB runtime needs to be fixed so that it doesn't need a manual restart.

**Comment by mstormi** [comment]
> This is an issue that effects everyone regardless of installation method right?

I believe so, yes. While initially it was for ZRAM, I don't need it any more for that.
There's a persistent general problem with OH, though.

> The openHAB runtime needs to be fixed so that it doesn't need a manual restart.

Agree. It just does not seem to be on OH core dev's agenda :(

But I'm fine with closing this without taking action.
