### ISSUE TITLE
Unknown date format Bad header data

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#170]
Users of the APT snapshot and testing repositories are met with the following error:

```
Err:# https://openhab.jfrog.io/openhab/openhab-linuxpkg testing Release
  Unknown date format Bad header data [IP: 35.231.52.82 443]
```

This is a known [issue in our current version of Artifactory](https://www.jfrog.com/jira/browse/RTFACT-21640) (6.18.1) which should be resolved if it is upgraded to 6.20.0.

Unable to fix from linuxpkg side, but posting for visibility.

**Comment by BClark09** [comment]
@kaikreuzer, are we able to update Artifactory ourselves?

**Comment by kaikreuzer** [comment]
No, afaik, we have no influence on the Artifactory version.
Only thing we could do is ask support for help.

How serious is it? Does it affect ALL users?

**Comment by BClark09** [comment]
I think it affects all users that are using the Artifactory repositories (unstable and testing). We can ask users to use the stable repo on Bintray for now so they can get 2.5.X patch releases, but it would be great if we can get the issue resolved.

**Comment by BClark09** [comment]
The problem seems to be intermittent too: it's working for me now, but wasn't an hour ago and all day yesterday.

**Comment by kaikreuzer** [comment]
Any latest observations on that topic?

**Comment by BClark09** [comment]
It's still working for me and we haven't had any recent posts on the forum about it. I wonder if there is a chance of it happening on each build, maybe it's stable right now because there hasn't been a successful snapshot build for a few days.

**Comment by kaikreuzer** [comment]
Yes, I did - their experts are looking into it and will come back to us.

**Comment by zombu2** [comment]
i guess their "experts" have no solution

**Comment by kaikreuzer** [comment]
@zombu2 You should better think twice before posting insulting comments. The guys are JFrog are awesome and that requests from non-paying customers of a free service might have a lower prio than others is perfectly understandable.

**Comment by BClark09** [comment]
Hi @kaikreuzer, did we get anyone come back to us? It'd be great if we are able to jump to 6.20.* to be clear of the issue, but I completely understand that this might take a bit of time still.

**Comment by kaikreuzer** [comment]
@BClark09 I reached out to them 2 weeks ago, but didn't get any answer so far - if I hear something, you'll be the first to know!

**Comment by Aspire1Inspire2** [comment]
On Ubuntu 18 LTS today:

Failed to fetch https://openhab.jfrog.io/openhab/openhab-linuxpkg/pool/main/2.5.10~S239/openhab2_2.5.10~S239-1_all.deb  Unknown date format Bad header data [IP: 35.231.52.82 443]

**Comment by hmerk** [comment]
Suspicious, error did not occur for a while until SNAPSHOT 2025 but reoccured on 2026...

**Comment by morph166955** [comment]
Having this on 3.0.0M3

apt-get update

    Err:8 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing Release
      Unknown date format Bad header data [IP: 35.231.52.82 443]
    E: The repository 'https://openhab.jfrog.io/openhab/openhab-linuxpkg testing Release' no longer has a Release file.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

apt-get upgrade

    E: Failed to fetch https://openhab.jfrog.io/openhab/openhab-linuxpkg/pool/main/3.0.0~M3/openhab_3.0.0~M3-1_all.deb  Unknown date format Bad header data [IP: 35.231.52.82 443]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    o

**Comment by kaikreuzer** [comment]
@BClark09 Eventually some good news: JFrog [announced a major cloud upgrade](https://www.jfrog.com/confluence/display/JFROG/What%27s+New%3A+Cloud), which includes Artifactory 7.0. I was just informed that our instance will be upgraded on Dec 3 (with some downtime on that day).

**Comment by BClark09** [comment]
Looks like that's done the trick, no issues so far! I'll close and reopen if there is any reoccurrence. Thanks @kaikreuzer!

**Comment by Dilepa** [comment]
i think its still happening.

`Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/openhab.jfrog.io_openhab_openhab-linuxpkg_dists_testing_main_binary-i386_Packages
E: The package lists or status file could not be parsed or opened.
FAILED (update apt lists)
`
