### ISSUE TITLE
files (re-)installation

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-linuxpkg#185]
I used to remove /etc/default/openhab2, uninstalled (apt remove) and re-installed the openhab2 package but the file was not installed again.
I haven't tried the same with other files but wouldn't think that is intentional ?

**Comment by BClark09** [comment]
Hi @mstormi, sorry I've just seen this.

This is normal behaviour of APT (dpkg). Deleting a file is seen as a configuration of that file so by default dpkg does not try to replace it.

```
sudo apt install --reinstall -o Dpkg::Options::="--force-confmiss" openhab2
```

(`openhab` for OH3)
