### ISSUE TITLE
Upgrade to OH3 doesn't work on Ubuntu Server 20.04.1 LTS

### ISSUE THREAD

**Issue by bccrew** [openhab/openhab-linuxpkg#194]
Fresh installed Ubuntu 20.04.1 LTS and updated to latest security updates.

When choosing option 42 as first step, it fails with following error. (logfile changed to debug=maximum)

    echo 'deb https://openhab.jfrog.io/openhab/openhab-linuxpkg testing main'
    ++ timestamp
    ++ date +%F_%T_%Z
    echo -n '2020-12-17_10:39:02_UTC [openHABian] Installing selected openHAB version... '
    2020-12-17_10:39:02_UTC [openHABian] Installing selected openHAB version... + cond_redirect apt-get update
    [[ -n '' ]]
    echo -e '\n\033[90;01m$ apt-get update \033[39;49;00m'

$ apt-get update

    apt-get update
    Hit:1 http://nl.archive.ubuntu.com/ubuntu focal InRelease
    Hit:2 http://nl.archive.ubuntu.com/ubuntu focal-updates InRelease
    Hit:3 http://nl.archive.ubuntu.com/ubuntu focal-backports InRelease
    Hit:4 http://nl.archive.ubuntu.com/ubuntu focal-security InRelease
    Get:5 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing InRelease [12.5 kB]
    Get:6 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing/main amd64 Packages [8,825 B]
    Get:7 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing/main i386 Packages [8,805 B]
    Fetched 30.1 kB in 2s (18.3 kB/s)
    Reading package lists... Error!
    E: Encountered a section with no Package: header
    E: Problem with MergeList /var/lib/apt/lists/openhab.jfrog.io_openhab_openhab-linuxpkg_dists_testing_main_binary-i386_Packages
    E: The package lists or status file could not be parsed or opened.

**Comment by BClark09** [comment]
Hi @bccrew, apologies for the delay in getting back to you!

The error you are receiving is due to a corrupted APT file, it's not necessarily specific to openHAB but the corrupt file seems one that apt has made for openHAB.

Try deleting the file:

```
sudo rm /var/lib/apt/lists/openhab*
```

and trying again.

**Comment by onik** [comment]
Hi, I have the same issue and deleting the files mentioned didn't help, the file is still corrupt.

```
[13:21:19] onik@openhab:~$ sudo rm /var/lib/apt/lists/openhab*
[13:21:41] onik@openhab:~$ sudo apt update && sudo apt upgrade
Hit:1 http://fi.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://fi.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://fi.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://fi.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://deb.nodesource.com/node_12.x focal InRelease
Hit:6 https://packages.grafana.com/oss/deb stable InRelease
Hit:7 https://repos.influxdata.com/ubuntu focal InRelease
Ign:8 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:9 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Get:10 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing InRelease [12.5 kB]
Get:12 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing/main amd64 Packages [9,040 B]
Get:13 https://openhab.jfrog.io/openhab/openhab-linuxpkg testing/main i386 Packages [9,108 B]
Fetched 36.7 kB in 1s (30.3 kB/s)
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/openhab.jfrog.io_openhab_openhab-linuxpkg_dists_testing_main_binary-i386_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by BClark09** [comment]
Hi @onik and @bccrew,

I have rebuilt the header information and tried this a test Ubuntu server, can you try again to see if the the problem is resolved?

```
sudo rm /var/lib/apt/lists/openhab*
sudo apt update
```

**Comment by onik** [comment]
@BClark09, I switched to Home Assistant so I can't test this anymore, sorry. Hope @bccrew will be able to confirm.

**Comment by BClark09** [comment]
No worries @onik, if you change your mind and still need the issue sorting then just let us know :)

**Comment by BClark09** [comment]
I've tested this on Ubuntu amd64, i386 and arm64 to be working. 

The repository files which are automatically generated for some architectures were corrupted. Recalculating index on the repository within Artifactory fixed this issue.

**Comment by bccrew** [comment]
Sorry, haven't got to testing anymore. Thanks anyways!
