### ISSUE TITLE
OpenHab3 breaks openhab-cli

### ISSUE THREAD

**Issue by UliPrantz** [openhab/openhab-linuxpkg#195]
Seems like openhab-cli is only working with the old directory structure of openhab2. Almost every command fails with a clean OH3 installation (without OH2 installed before). 

# Some Examples:

## openhab-cli info
```
openhab-cli info

awk: Fatal: Die Datei „/var/lib/openhab2/etc/version.properties“ kann nicht zum Lesen geöffnet werden (Datei oder Verzeichnis nicht gefunden)
awk: Fatal: Die Datei „/var/lib/openhab2/etc/version.properties“ kann nicht zum Lesen geöffnet werden (Datei oder Verzeichnis nicht gefunden)
```
## openhab-cli console
```
openhab-cli console

/usr/bin/openhab-cli: 107: /usr/share/openhab2/runtime/bin/client: not found
```

## openhab-cli showlogs
```
openhab-cli showlogs

tail: '/var/log/openhab2/*.log' kann nicht zum Lesen geöffnet werden: Datei oder Verzeichnis nicht gefunden
tail: Keine Dateien mehr übrig
```

All of them depend on the old directory structure.
Most of these locations exist but just with `openhab` instead of `openhab2`.

# System Info
I'm running Ubuntu 20.4.1 x64 with 5.4.0-58-generic kernel

## Java version (output of `java --verison`)
```
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
``` 

## OpenHab3 installation
Installed OH3 with the official installation guide using apt.

**Comment by BClark09** [comment]
Hi @UliPrantz,

I can't replicate this, can you check that the contents of `/usr/bin/openhab-cli` matches the [one that is packaged](https://github.com/openhab/openhab-linuxpkg/blob/master/resources/usr/bin/openhab-cli).

What is the result of `apt-cache policy openhab` and `apt-cache policy openhab2`?

**Comment by UliPrantz** [comment]
Never mind I just did nothing for the night (maybe it was a automatic scheduled reboot) now it works. Thanks anyways.
