### ISSUE TITLE
PackageKit error: downloadSubjectPublicKey?username=openhab is not a public key

### ISSUE THREAD

**Issue by dwrobel** [openhab/openhab-linuxpkg#196]
I'm observing that [cockpit](https://cockpit-project.org/running) on FedoraServer 33 is not able to show available package updates due to the following error:
>downloadSubjectPublicKey?username=openhab is not a public key

Cockpit screenshot:
![Screenshot_2021-01-06 Software Updates - root localhost localdomain](https://user-images.githubusercontent.com/228873/103779212-b7139480-5033-11eb-89f1-5fd1708df671.png)

The problem seems to be in the URL which contains question mark but it is not quoted. The following change fixes the problem:

```
# diff -u /etc/yum.repos.d/openhab-stable.repo.orig /etc/yum.repos.d/openhab-stable.repo 
--- /etc/yum.repos.d/openhab-stable.repo.orig	2021-01-05 13:14:49.761690534 +0100
+++ /etc/yum.repos.d/openhab-stable.repo	2021-01-06 15:13:57.951235000 +0100
@@ -2,5 +2,5 @@
 name=openHAB 2.x.x Stable
 baseurl=https://dl.bintray.com/openhab/rpm-repo2/stable
 gpgcheck=1
-gpgkey=https://bintray.com/user/downloadSubjectPublicKey?username=openhab
+gpgkey="https://bintray.com/user/downloadSubjectPublicKey?username=openhab"
 enabled=1
```
Cockpit with the fix applied:
![Screenshot_2021-01-06 Software Updates - root localhost localdomain(1)](https://user-images.githubusercontent.com/228873/103779555-3903bd80-5034-11eb-9a26-bc0a20c32ac3.png)

However, I'm not aware who is responsible for generating the `openhab-stable.repo` file.

**Comment by BClark09** [comment]
Good catch @dwrobel, thanks for sending the PR on the Docs too!

One thing I'd like to do is include the `.repo` file within the package, so will remember this for next time. :)
