### ISSUE TITLE
org.apache.karaf.shell.cfg

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-linuxpkg#203]
A package upgrade/install should not overwrite /var/lib/openhab/etc/`org.apache.karaf.shell.cfg` but keep any existing
else users have to modify it every time e.g. for the IP addresses the console listens on (only localhost by default - worth a thought to make that "all", too, given that key based auth is available).

**Comment by BClark09** [comment]
`/var/lib/openhab/etc/org.apache.karaf.shell.cfg` is listed as a system file in: [userdata_sysfiles.lst](https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/userdata_sysfiles.lst)

Can the these settings be configured `$OPENHAB_CONF/services/runtime.cfg`

e.g:

```
org.apache.karaf.shell:sshHost = <ip>
```

This would be the most appropriate place to put user written configuration.

**Comment by mstormi** [comment]
hmm no I don't think so. I tried with host ip and 0.0.0.0 but it didn't allow connecting to console.

**Comment by mstormi** [comment]
Changed openHABian to use runtime.cfg now.
