### ISSUE TITLE
Automatic updates with ppa (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Huaba** [openhab/openhab-linuxpkg#21]
_on your request here: https://github.com/openhab/openhab-distro/issues/327_

I've installed openhab2-offline with the snapshot ppa. My system installs updates every night. After more updates openhab doesn't run without a complete system reboot.

All UI's have an "ERR_CONNECTION_REFUSED" in the browser, and "sudo service openhab2 status" returns a "Ignoring predefined value for KARAF_HOME - status: Not running..."

An "ps -ef | grep openhab" return a lot of running processes (actually 8).

Any hint to prevent this behavior for a openhab noob?

At the moment i've stopped the automatic updates for openhab with "sudo apt-mark hold openhab2", but this is only a workaround :)

Thx for your great work, i love Openhab!

Huaba

**Comment by BClark09** [comment]
Hi @Huaba, I've begun to look into this, and just wanted to clarify something. You've added the bintray repo to Ubuntu using Software & Updates and are updating via the built in software updater?

**Comment by Huaba** [comment]
Hi @BClark09, i've installed the snapshot releases of openhab2-offline. I used the tutorial in docs.openhab.org: http://docs.openhab.org/installation/linux.html#package-repository-installation

The openhab2-offline runs on a Ubuntu 14.04 Server with no GUI and apt is configured to make automatically all updates at 21:30 every day.

**Comment by ralle12345** [comment]
Dunno if that is related to this issue, but I get the same error message when I try to stop openhab2 with _service openhab2 stop_

This is 2.0.0 release also on Ubuntu 14.04.

**Comment by BClark09** [comment]
With the latest snapshots of openhab, this should no longer be an issue. I've had automatic updates work quite well since the merge of  #30. Can you let me know if this is the same for you? I'll close this issue soon.

Note that if you're still on openhab2-offline packages, you will need to move to the openhab2 package manually first.
