### ISSUE TITLE
Suggest Java 17 package installation for openHAB 4

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-linuxpkg#216]
With #215 the [openHAB-Linuxpkg](https://ci.openhab.org/job/openHAB-Linuxpkg/) build succeeds for OH 4.

Though the packages probably may need some additional updates for OH 4.
E.g. the "suggests" should be updated because Java 17 is required:

https://github.com/openhab/openhab-linuxpkg/blob/c6122618a155d60dd027f6e92c4f52b08f8e2df3/build.gradle#L207

**Comment by BClark09** [comment]
Thanks @wborn, default-jre for most distributions usually points to Java 11 at the moment. So we may need to change it to something like:

`suggests('openjdk-17-jdk |  java17-runtime  |  java17-runtime-headless')`

I'm assuming openHAB 3 will still get patches? Will need to consider if we should have different branches for the meantime.

**Comment by wborn** [comment]
Yes more OH 3.4 releases with patches are to be expected.

**Comment by BClark09** [comment]
Thanks @wborn, I've have made the above pull request. 

I've have created a 3.x branch - we should use this in any Jenkins build that patches 3.4.
