### ISSUE TITLE
init.d restart does not wait for process to stop

### ISSUE THREAD

**Issue by abedwardsw** [openhab/openhab-linuxpkg#30]
- restart should wait for process to stop, otherwise it doesn't work
- stop, if the pidfile is incorrect, then it should also check for the existing process and stop it
- rework into functions so we can re-use logic for stop/start in the restart call

**Comment by abedwardsw** [comment]
Not sure if I am supposed to create a ticket in addition to a pull request.   If not, we can close this ticket and work from the pull request comments.

Please see https://github.com/openhab/openhab-linuxpkg/pull/31

**Comment by BClark09** [comment]
No worries, this is a duplicate issue of #28 but we can link to close both when the PR is merged by following what I said there.

**Comment by abedwardsw** [comment]
@BClark09 will you use my PR ?  it seems to work fine, been testing it at home.

**Comment by BClark09** [comment]
@abedwardsw I have made the appropriate comments on the PR, let's continue the discussion there.
