### ISSUE TITLE
Openhab user is not member of audio group

### ISSUE THREAD

**Issue by claus007** [openhab/openhab-linuxpkg#35]
The openhab user created is not a member of the audio group. This is necessary of course to play audio.
This is a small issue but if you don't know it can take a while. Foremost because there isn't any error logged.

Linux distro: Ubuntu 16.04

**Comment by BClark09** [comment]
Depending on the setup of the user, automatically assigning openHAB to the audio group may be a [bad idea](https://wiki.ubuntu.com/Audio/TheAudioGroup).  Like other periferals, we should probably add this to a reccomended step in the documentation. Would you (and @ThomDietrich) agree?

**Comment by ThomDietrich** [comment]
Could find it's place here: http://docs.openhab.org/installation/linux.html#privileges-for-common-peripherals
@claus007 please feel free to add your contribution: https://github.com/openhab/openhab-docs/edit/gh-pages/installation/linux.md

I want to add that "Foremost because there isn't any error logged." can be seen as a bug. Would you please file an issue over at https://github.com/eclipse/smarthome/issues/new

**Comment by ThomDietrich** [comment]
Docs changes were merged, I'd still like to encourage @claus007 to file a bug report!

**Comment by claus007** [comment]
As requested filled out a new error report.
#3120

And I also read the "bad idea" - on one hand they're right - but what is the alternative ? You could use pulse audio instead - but this is run either from user currently logged in, or as system daemon, but as far as I know then there is no shared memory available (don't know how bad this is).

**Comment by BClark09** [comment]
There wouldn't be an alternative per se, adding the audio group is the right thing to do for a system user like openhab, and has been added to the setup page for Linux. However, I feel like those wanting to keep strict permissions for openHAB might disagree with adding all system peripherals automatically, especially if there's a chance it will conflict with another service accessing the device.

**Comment by claus007** [comment]
:-) this looks like a good solution: https://en.wikipedia.org/wiki/Sticky_bit

A file with the according rights will be shipped along with openhab. Big advantage is, instead of messing up user rights - there is one file which can be used in the first step - if the user finds a better solution he may also delete this file.
