### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-linuxpkg#4]
Please add a CONTRIBUTING.md file similar to https://github.com/openhab/openhab-docker/blob/master/CONTRIBUTING.md and make sure that all @openhab/linuxpkg-maintainers follow these rules themselves, i.e. add new content only through PRs, correctly sign-off commits, etc. Many thanks!

**Comment by BClark09** [comment]
I've tried to submit a PR for it, but I don't think I'm off to a good start, somehow managed to create a branch through openhab instead of my own fork. Sorry! 🙏
