### ISSUE TITLE
Higher maturity packages should be in lower distributions too

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#56]
### DEB 

- [x] Setup separated list of distributions for Deb packages.

### RPM

Choose between:

 - [ ] RPM Packages need to be duplicated across different directories. Upload multiple times.
 - [x] Leave RPM Packages as they are, documentation already suggests adding multiple this way.

**Comment by BClark09** [comment]
@ThomDietrich ;)

**Comment by ThomDietrich** [comment]
Thanks ;)

**Comment by BClark09** [comment]
@ThomDietrich I've updated the description. For RPM formats there is no way of being able have having one file for multiple repos, and I think the RPM spec recommends against having a single package in one place. In your opinion, is the option selected for RPM the most appropriate one?

**Comment by ThomDietrich** [comment]
I'm struggling to decide. For me it feels natural to have the newest stable version in all repositories as long as there is no testing or snapshot build. So I would tend towards option 1 - **however** it might be an idea to check other repositories and how they handle cases like this. Did you do that?

**Comment by BClark09** [comment]
I found very few examples of snapshot directories, but none of them had stable rpms inside the lower distributions.

[1](http://yum.stratuslab.eu/), asks to add either snapshot or stable. If you look at what snapshot provides, you'll see no stable rpm version.
[2](http://www.graphviz.org/graphviz-rhel.repo) is an example repo file, much like we are currently suggesting for openHAB, again same as above.

It makes more sense to to it this way for RPM than it would for Debian, because generally the contents must be much stricter and relevant to single files. If you have two files coming from the same place you need to make sure that they're identical. There's no unstable -> testing -> stable pattern in CentOS or Redhat either.
