### ISSUE TITLE
Require default-jdk-headless

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#58]
- [x] Find out minimum version in terms of above package version.
 - [x] Add to openhab2 package version requirements.

**Comment by ThomDietrich** [comment]
Good idea! Are you fixed on default-jdk-headless? Zulu doesn't seem to provide this virtual package.

**Comment by BClark09** [comment]
Ah good catch, also default-jdk-headless may not install java 8 at all! I should be able to depend on the following to cover all:

```
java8-jdk | java8-sdk-headless | java8-sdk | java8-runtime-headless
```

That said, it[ shouldn't](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps) *depend* on java 8 but *recommend* it instead. That way, those who have installed java manually would not have issues.

**Comment by ThomDietrich** [comment]
Great, seems to cover all the big three, looking at the `Provides` of all of them maybe you want to also add java8-runtime (of the Java 8 packages Zulu only provides java8-jdk and java8-runtime). 

`Recommends` seems like a good choice :+1:

**Comment by BClark09** [comment]
Eek, looks like these virtual packages are a mess.

java9* virtual package provides java8* virtual packages, so if you recommend or depend on the above then it will automatically choose to install java 9, which is incompatible with openHAB 2. What's worse is that there seems to be no way of specifying a maximum version for these virtual packages.

I understand java8 containing java7 virtual packages, Java 8 is fairly backwards compatible. Java 9 however is not.

Related: https://bugs.launchpad.net/ubuntu/+source/openjdk-9/+bug/1584118

**Comment by ThomDietrich** [comment]
Okay... wow, this is the key problem:

> it is technically correct that java9 does provide a java8-runtime, but java9 isn't even released yet and should definitely not be the default java8-runtime until that time

I agree with the second part but openHAB needs to be properly tested with Java 9 before it can even be considered. Hence that should not be an option at all. The first part makes sense but totally messes with the initial idea.

What's your suggestion? `Recommends: zulu-embedded-8 | oracle-java8-jdk | openjdk-8-jre-headless`

**Comment by BClark09** [comment]
openHAB fails to start on openjdk-9, but that is a problem for another day.

Since oracle-java8-jdk is a provided by oracle-java9-installer I think it'll have to be oracle-java8-installer specifically.

**Comment by ThomDietrich** [comment]
I know, I've written the docs sentence saying so :smile_cat:

**Comment by BClark09** [comment]
One last use case, someone has manually installed oracle linux, and then tries to install openHAB2.

Even with recommends it'll install openjdk, which would be less stable. Is this something that we should seek to avoid?

**Comment by BClark09** [comment]
>I know, I've written the docs sentence saying so 😸

Haha, sorry. I should really read them more often ;)
