### ISSUE TITLE
Installation should not include .bat or contrib files.

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#73]
The purpose of openhab-linuxpkg is to provide a fully configured (but editable) installation of openHAB 2. There should be no need to package the .bat files in `/usr/share/openhab2`, nor should the service templates exist in `/usr/share/openhab2/runtime/bin/contrib` as these are provided already. Seems wasteful to include them in the package and should therefore be excluded.

@ThomDietrich wdyt?

**Comment by BClark09** [comment]
Also, `/usr/share/openhab2/runtime/bin/update` can be replaced with a simple message asking to apt-get or yum/dnf.

**Comment by ThomDietrich** [comment]
Agree on both points. Including the bats is dead weight and the other files are not needed and should hence not exist in the first place. All these files will just clutter the users file system and mislead them into thinking they are of value.
