### ISSUE TITLE
Add /usr/bin/openhab

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#77]
There should be a set of openhab commands that are easy to use and fairly self explanatory. Ones I can think of:

```
Usage:  openhab command [options]

Possible commands:
  start                          -- Starts openHAB as a daemon service.
  stop                           -- Stops an existing openHAB daemon service.
  restart                        -- Stops then starts an openHAB daemon service.
  status                         -- Checks to see if openHAB is running or prints systemctl status.
  console                        -- Opens the openHAB console.
  backup [filename]              -- Stores the current configuration of openHAB.
  restore filename               -- Restores the state of openHAB to a backup.
  showlogs [-l lines] ] [--tail] -- Displays the last log messages of openHAB.
```

@ThomDietrich, think of any more?

**Comment by ThomDietrich** [comment]
Ah you are thinking about a separate script for this?

I like the idea to combine everything into one handy (documented) command. I'm undecided if another "onion layer" is beneficial...

In openHABian there are a few aliases for these kinds of things but I never extended or promoted them much...

Be aware, that some of these commands need root, while others don't. A symlink to /usr/sbin seems to be common.

**Comment by BClark09** [comment]
> A symlink to /usr/sbin seems to be common.

![image](https://user-images.githubusercontent.com/8983584/29027182-74bfe9d8-7b77-11e7-933e-522da1b12336.png)

Any resources you have on this? All I could find was a general agreement that scripts that need root access should go in `/usr/sbin` only. Is there any reason to have them in both?

**Comment by ThomDietrich** [comment]
![spidey-meme](https://user-images.githubusercontent.com/2870104/29027469-1a27e606-7b81-11e7-82bc-10c11851ed86.jpg)

Nevermind. 😛

**Comment by BClark09** [comment]
Haha!

Since we're doing this, should a man entry be necessary?

**Comment by ThomDietrich** [comment]
Doesn't hurt but I'd say it's not needed. Maybe at a later point.

You've changed the issue name to sbin. That's not what I wanted to suggest. The script can reside in bin, it already has its internal root checking. some commands like status or log don't even need root privileges.

**Comment by BClark09** [comment]
Ah I see, that makes sense, having a look at the scripts that already exist using:

```
grep -rl '^#!/.*sh' /usr/bin
```

It looks like they do the same (e.g. raspi-config). Back we go!!!

**Comment by BClark09** [comment]
Untested example of what I had planned:

https://gist.github.com/BClark09/4e98b9e2dc6a372f02ede1fae130df27

**Comment by ThomDietrich** [comment]
Looks good! Nice thing about it is, that you can recycle a lot from other scripts :D

**Comment by BClark09** [comment]
> You are exporting HTTP_PORT without making sure it exists

Sorry, recycled too hard... It won't need HTTP_PORT as this would be checked elsewhere. Other paths may not used in the script may not be needed either.

Indeed, the log command should be the only command that'll need some code snippet not already used elsewhere in linuxpkg. Will have a think about that when I have the time to test! Thanks!

**Comment by ThomDietrich** [comment]
@BClark09 this might be far fetched but take a minute to think about it:
The longer I think about the options of this script and the ways it could be extended over time, I wonder if we should discuss how the openhabian-config program could be re-purposed in that matter. It is already quite capable and can offer many things every apt based installation can benefit from. Options as the above are easily added. RPM support can be added and the script would probably benefit from a broader developer base.
I'm talking long run here, for now the PR is fine as it is and should be merged.

**Comment by BClark09** [comment]
Sorry, I'm a little unsure what you mean, are you suggesting to include the features of openhabian-config into this script?

**Comment by ThomDietrich** [comment]
Hey @BClark09, I'm sorry I forgot to answer.
I meant it the other way around. I wonder if instead of maintaining a new script/management tool, we could use openhabian-config for that task. The script is already capable to do a lot of things and could easily handle the few extra tasks your script provides.

Another question: This might come a bit late but may I ask if you thought about another name for the script? `openhab` as a command seems a bit mistakable. Typical alternatives are names like `systemctl` or `gitlab-cli`

**Comment by BClark09** [comment]
I see, so you'd rather call `openhab-cli backup` etc from within openhabian-config? Makes sense, and this script can be extended to cover distribution specific tasks.

I can certainly change the name now, I haven't announced it yet and no one has downloaded the snapshot. `openhab-cli` makes sense to me, and I've seen many other programs do this.

**Comment by ThomDietrich** [comment]
> I can certainly change the name now

Now is the last chance, I thought so too. Alternatives are `openhab-cli`, `openhab-cmd`, `openhab-ctl` However please do not feel urged to rename it, this is up to you.
