### ISSUE TITLE
Restore command description

### ISSUE THREAD

**Issue by marcelerkel** [openhab/openhab-linuxpkg#89]
backup [filename]      -- Stores the current configuration of openHAB.
    restore filename       -- Restores the state of openHAB to a backup.

I'm not a native English speaker, but should it not be "Restores the state of openHAB from a backup" (instead of "to a backup")?
Also, I think "state" could be confused with item state but I guess we're talking about configuration state, so how about:

    backup [filename]      -- Stores the current configuration of openHAB.
    restore filename       -- Restores the configuration of openHAB from a backup.

Anyway, a great addition! I will definitely use the backup feature and hopefully never need to use the restore feature :)

**Comment by BClark09** [comment]
Hi @marcelerkel, Thanks for bring it up! 

I'd agree that it doesn't read as well as it should. I'm going to be reducing the spacing a bit so that it fits in the standard PuTTy terminal soon. So will implement what you suggest during that change. 
😊
