### ISSUE TITLE
build does not work from Windows

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-linuxpkg#92]
I'm not sure if anything can be done about this, every important file is replaced with Windows style line endings.

Twice I've fallen into the trap of building a change on my windows machine, to thoroughly screw-up the state of dpkg on my linux machine when I go to test it.

Might be best to remove gradle.bat and simply expect that Linux packages should be built on Linux...

**Comment by ThomDietrich** [comment]
Not sure which direction we are talking. Are the Windows endings (CRLF) committed or are you copying them over? Git allows to define how files are committed, you can force LF-only.

**Comment by BClark09** [comment]
It's gradle side. The copy task copies a file from the directory into the deb package, but it changes the line endings to whatever the OS uses.

**Comment by ThomDietrich** [comment]
Ah I see. That's why I'm using Vagrant machines for these kinds of tasks 😃

**Comment by ThomDietrich** [comment]
@BClark09 are we going to meet at the Smart Home Day?

**Comment by BClark09** [comment]
Unfortunately not :disappointed:. It would have been good to meet up over what looks like will be a fantastic day! This time of the year is usually a really busy period for me though :weary:. 

I hope the event (and your session) goes well, but I'm sure it will. :D

**Comment by ThomDietrich** [comment]
Too bad 😉 Enjoy your weekend!!
